// <auto-generated />
using System;
using Blacksmith.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blacksmith.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250106165224_NewDb")]
    partial class NewDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blacksmith.WebApi.Models.GameData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameData");
                });

            modelBuilder.Entity("Blacksmith.WebApi.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseAttackPower")
                        .HasColumnType("int");

                    b.Property<int>("BaseAttackSpeed")
                        .HasColumnType("int");

                    b.Property<int>("BaseDurability")
                        .HasColumnType("int");

                    b.Property<int>("BaseMagicPower")
                        .HasColumnType("int");

                    b.Property<int>("BasePrice")
                        .HasColumnType("int");

                    b.Property<int>("BaseProtectionMagic")
                        .HasColumnType("int");

                    b.Property<int>("BaseProtectionPhysical")
                        .HasColumnType("int");

                    b.Property<int>("BaseScore")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<bool>("Tradable")
                        .HasColumnType("bit");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Blacksmith.WebApi.Models.Items.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Blacksmith.WebApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenExp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Blacksmith.WebApi.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameDataId")
                        .HasColumnType("int");

                    b.Property<string>("LoginCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoginCodeExp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("GameDataId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared_Classes.Models.TestPotato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestPotatoes");
                });

            modelBuilder.Entity("Blacksmith.WebApi.Models.GameData", b =>
                {
                    b.OwnsMany("Blacksmith.WebApi.Models.Items.MaterialQuantity", "UserMaterials", b1 =>
                        {
                            b1.Property<int>("GameDataId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("MaterialId")
                                .HasColumnType("int");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("GameDataId", "Id");

                            b1.ToTable("GameData");

                            b1.ToJson("UserMaterials");

                            b1.WithOwner()
                                .HasForeignKey("GameDataId");
                        });

                    b.OwnsMany("Blacksmith.WebApi.Models.Items.ItemCrafted", "UserItems", b1 =>
                        {
                            b1.Property<int>("GameDataId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("Durability")
                                .HasColumnType("int");

                            b1.Property<int>("ItemId")
                                .HasColumnType("int");

                            b1.Property<int>("PrefixId")
                                .HasColumnType("int");

                            b1.Property<int>("Price")
                                .HasColumnType("int");

                            b1.Property<int>("Score")
                                .HasColumnType("int");

                            b1.Property<int>("SuffixId")
                                .HasColumnType("int");

                            b1.HasKey("GameDataId", "Id");

                            b1.ToTable("GameData");

                            b1.ToJson("UserItems");

                            b1.WithOwner()
                                .HasForeignKey("GameDataId");
                        });

                    b.Navigation("UserItems");

                    b.Navigation("UserMaterials");
                });

            modelBuilder.Entity("Blacksmith.WebApi.Models.Items.Item", b =>
                {
                    b.OwnsMany("Blacksmith.WebApi.Models.Items.MaterialQuantity", "Recipe", b1 =>
                        {
                            b1.Property<int>("ItemId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("MaterialId")
                                .HasColumnType("int");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("ItemId", "Id");

                            b1.ToTable("Items");

                            b1.ToJson("Recipe");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Blacksmith.WebApi.Models.RefreshToken", b =>
                {
                    b.HasOne("Blacksmith.WebApi.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blacksmith.WebApi.Models.UserModel", b =>
                {
                    b.HasOne("Blacksmith.WebApi.Models.GameData", "GameData")
                        .WithMany()
                        .HasForeignKey("GameDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Blacksmith.WebApi.Models.AccountStatus", "AccountStatus", b1 =>
                        {
                            b1.Property<int>("UserModelId")
                                .HasColumnType("int");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("StatusExp")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Validated")
                                .HasColumnType("bit");

                            b1.HasKey("UserModelId");

                            b1.ToTable("Users");

                            b1.ToJson("AccountStatus");

                            b1.WithOwner()
                                .HasForeignKey("UserModelId");
                        });

                    b.OwnsOne("Blacksmith.WebApi.Models.LoginStatus", "LoginStatus", b1 =>
                        {
                            b1.Property<int>("UserModelId")
                                .HasColumnType("int");

                            b1.Property<int>("LoginAttempts")
                                .HasColumnType("int");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StatusCode")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserModelId");

                            b1.ToTable("Users");

                            b1.ToJson("LoginStatus");

                            b1.WithOwner()
                                .HasForeignKey("UserModelId");
                        });

                    b.Navigation("AccountStatus")
                        .IsRequired();

                    b.Navigation("GameData");

                    b.Navigation("LoginStatus")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
