// <auto-generated />
using Blacksmith.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blacksmith.WebApi.Migrations.DbContextSqliteMigrations
{
    [DbContext(typeof(DbContextSqlite))]
    partial class DbContextSqliteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Blacksmith.WebApi.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseAttackPower")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseAttackSpeed")
                        .HasColumnType("REAL");

                    b.Property<int>("BaseDurability")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseMagicPower")
                        .HasColumnType("REAL");

                    b.Property<int>("BasePrice")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseProtectionMagic")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseProtectionPhysical")
                        .HasColumnType("REAL");

                    b.Property<int>("BaseScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tradable")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Blacksmith.WebApi.Models.Items.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Blacksmith.WebApi.Models.Items.Item", b =>
                {
                    b.OwnsMany("Shared_Classes.Models.MaterialQuantity", "Recipe", b1 =>
                        {
                            b1.Property<int>("ItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaterialId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ItemId", "Id");

                            b1.ToTable("Items");

                            b1.ToJson("Recipe");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Recipe");
                });
#pragma warning restore 612, 618
        }
    }
}
